//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.5
//
// <auto-generated>
//
// Generated from file `iTransformServer.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __iTransformServer_h__
#define __iTransformServer_h__

#include <IceUtil/PushDisableWarnings.h>
#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/ValueF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Comparable.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/GCObject.h>
#include <Ice/Value.h>
#include <Ice/Incoming.h>
#include <Ice/FactoryTableInit.h>
#include <IceUtil/ScopedArray.h>
#include <Ice/Optional.h>
#include <IceUtil/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 >= 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 5
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace iTransformServer
{

class iDataServer;
class iDataServerPrx;

}

namespace iTransformServer
{

using byteArray = ::std::vector<::Ice::Byte>;

struct Result
{
    ::std::string decoder;
    ::iTransformServer::byteArray data;

    /**
     * Obtains a tuple containing all of the struct's data members.
     * @return The data members in a tuple.
     */
    std::tuple<const ::std::string&, const ::iTransformServer::byteArray&> ice_tuple() const
    {
        return std::tie(decoder, data);
    }
};

using Ice::operator<;
using Ice::operator<=;
using Ice::operator>;
using Ice::operator>=;
using Ice::operator==;
using Ice::operator!=;

}

namespace iTransformServer
{

class iDataServer : public virtual ::Ice::Object
{
public:

    using ProxyType = iDataServerPrx;

    /**
     * Determines whether this object supports an interface with the given Slice type ID.
     * @param id The fully-scoped Slice type ID.
     * @param current The Current object for the invocation.
     * @return True if this object supports the interface, false, otherwise.
     */
    virtual bool ice_isA(::std::string id, const ::Ice::Current& current) const override;

    /**
     * Obtains a list of the Slice type IDs representing the interfaces supported by this object.
     * @param current The Current object for the invocation.
     * @return A list of fully-scoped type IDs.
     */
    virtual ::std::vector<::std::string> ice_ids(const ::Ice::Current& current) const override;

    /**
     * Obtains a Slice type ID representing the most-derived interface supported by this object.
     * @param current The Current object for the invocation.
     * @return A fully-scoped type ID.
     */
    virtual ::std::string ice_id(const ::Ice::Current& current) const override;

    /**
     * Obtains the Slice type ID corresponding to this class.
     * @return A fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

    virtual Result postMessage(byteArray cmd, const ::Ice::Current& current) = 0;
    /// \cond INTERNAL
    bool _iceD_postMessage(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    virtual byteArray getMessage(byteArray cmd, const ::Ice::Current& current) = 0;
    /// \cond INTERNAL
    bool _iceD_getMessage(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    /// \cond INTERNAL
    virtual bool _iceDispatch(::IceInternal::Incoming&, const ::Ice::Current&) override;
    /// \endcond
};

}

namespace iTransformServer
{

class iDataServerPrx : public virtual ::Ice::Proxy<iDataServerPrx, ::Ice::ObjectPrx>
{
public:

    Result postMessage(const byteArray& cmd, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _makePromiseOutgoing<::iTransformServer::Result>(true, this, &iDataServerPrx::_iceI_postMessage, cmd, context).get();
    }

    template<template<typename> class P = ::std::promise>
    auto postMessageAsync(const byteArray& cmd, const ::Ice::Context& context = ::Ice::noExplicitContext)
        -> decltype(::std::declval<P<::iTransformServer::Result>>().get_future())
    {
        return _makePromiseOutgoing<::iTransformServer::Result, P>(false, this, &iDataServerPrx::_iceI_postMessage, cmd, context);
    }

    ::std::function<void()>
    postMessageAsync(const byteArray& cmd,
                     ::std::function<void(::iTransformServer::Result)> response,
                     ::std::function<void(::std::exception_ptr)> ex = nullptr,
                     ::std::function<void(bool)> sent = nullptr,
                     const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _makeLamdaOutgoing<::iTransformServer::Result>(std::move(response), std::move(ex), std::move(sent), this, &iTransformServer::iDataServerPrx::_iceI_postMessage, cmd, context);
    }

    /// \cond INTERNAL
    void _iceI_postMessage(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<::iTransformServer::Result>>&, const byteArray&, const ::Ice::Context&);
    /// \endcond

    byteArray getMessage(const byteArray& cmd, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _makePromiseOutgoing<::iTransformServer::byteArray>(true, this, &iDataServerPrx::_iceI_getMessage, cmd, context).get();
    }

    template<template<typename> class P = ::std::promise>
    auto getMessageAsync(const byteArray& cmd, const ::Ice::Context& context = ::Ice::noExplicitContext)
        -> decltype(::std::declval<P<::iTransformServer::byteArray>>().get_future())
    {
        return _makePromiseOutgoing<::iTransformServer::byteArray, P>(false, this, &iDataServerPrx::_iceI_getMessage, cmd, context);
    }

    ::std::function<void()>
    getMessageAsync(const byteArray& cmd,
                    ::std::function<void(::iTransformServer::byteArray)> response,
                    ::std::function<void(::std::exception_ptr)> ex = nullptr,
                    ::std::function<void(bool)> sent = nullptr,
                    const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _makeLamdaOutgoing<::iTransformServer::byteArray>(std::move(response), std::move(ex), std::move(sent), this, &iTransformServer::iDataServerPrx::_iceI_getMessage, cmd, context);
    }

    /// \cond INTERNAL
    void _iceI_getMessage(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<::iTransformServer::byteArray>>&, const byteArray&, const ::Ice::Context&);
    /// \endcond

    /**
     * Obtains the Slice type ID of this interface.
     * @return The fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

protected:

    /// \cond INTERNAL
    iDataServerPrx() = default;
    friend ::std::shared_ptr<iDataServerPrx> IceInternal::createProxy<iDataServerPrx>();

    virtual ::std::shared_ptr<::Ice::ObjectPrx> _newInstance() const override;
    /// \endcond
};

}

/// \cond STREAM
namespace Ice
{

template<>
struct StreamableTraits<::iTransformServer::Result>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 2;
    static const bool fixedLength = false;
};

template<typename S>
struct StreamReader<::iTransformServer::Result, S>
{
    static void read(S* istr, ::iTransformServer::Result& v)
    {
        istr->readAll(v.decoder, v.data);
    }
};

}
/// \endcond

/// \cond INTERNAL
namespace iTransformServer
{

using iDataServerPtr = ::std::shared_ptr<iDataServer>;
using iDataServerPrxPtr = ::std::shared_ptr<iDataServerPrx>;

}
/// \endcond

#else // C++98 mapping

namespace IceProxy
{

namespace iTransformServer
{

class iDataServer;
/// \cond INTERNAL
void _readProxy(::Ice::InputStream*, ::IceInternal::ProxyHandle< iDataServer>&);
::IceProxy::Ice::Object* upCast(iDataServer*);
/// \endcond

}

}

namespace iTransformServer
{

class iDataServer;
/// \cond INTERNAL
::Ice::Object* upCast(iDataServer*);
/// \endcond
typedef ::IceInternal::Handle< iDataServer> iDataServerPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::iTransformServer::iDataServer> iDataServerPrx;
typedef iDataServerPrx iDataServerPrxPtr;
/// \cond INTERNAL
void _icePatchObjectPtr(iDataServerPtr&, const ::Ice::ObjectPtr&);
/// \endcond

}

namespace iTransformServer
{

typedef ::std::vector< ::Ice::Byte> byteArray;

struct Result
{
    ::std::string decoder;
    ::iTransformServer::byteArray data;
};

}

namespace iTransformServer
{

/**
 * Base class for asynchronous callback wrapper classes used for calls to
 * IceProxy::iTransformServer::iDataServer::begin_postMessage.
 * Create a wrapper instance by calling ::iTransformServer::newCallback_iDataServer_postMessage.
 */
class Callback_iDataServer_postMessage_Base : public virtual ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_iDataServer_postMessage_Base> Callback_iDataServer_postMessagePtr;

/**
 * Base class for asynchronous callback wrapper classes used for calls to
 * IceProxy::iTransformServer::iDataServer::begin_getMessage.
 * Create a wrapper instance by calling ::iTransformServer::newCallback_iDataServer_getMessage.
 */
class Callback_iDataServer_getMessage_Base : public virtual ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_iDataServer_getMessage_Base> Callback_iDataServer_getMessagePtr;

}

namespace IceProxy
{

namespace iTransformServer
{

class iDataServer : public virtual ::Ice::Proxy<iDataServer, ::IceProxy::Ice::Object>
{
public:

    ::iTransformServer::Result postMessage(const ::iTransformServer::byteArray& cmd, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return end_postMessage(_iceI_begin_postMessage(cmd, context, ::IceInternal::dummyCallback, 0, true));
    }

    ::Ice::AsyncResultPtr begin_postMessage(const ::iTransformServer::byteArray& cmd, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _iceI_begin_postMessage(cmd, context, ::IceInternal::dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_postMessage(const ::iTransformServer::byteArray& cmd, const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_postMessage(cmd, ::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_postMessage(const ::iTransformServer::byteArray& cmd, const ::Ice::Context& context, const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_postMessage(cmd, context, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_postMessage(const ::iTransformServer::byteArray& cmd, const ::iTransformServer::Callback_iDataServer_postMessagePtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_postMessage(cmd, ::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_postMessage(const ::iTransformServer::byteArray& cmd, const ::Ice::Context& context, const ::iTransformServer::Callback_iDataServer_postMessagePtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_postMessage(cmd, context, cb, cookie);
    }

    ::iTransformServer::Result end_postMessage(const ::Ice::AsyncResultPtr& result);

private:

    ::Ice::AsyncResultPtr _iceI_begin_postMessage(const ::iTransformServer::byteArray&, const ::Ice::Context&, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& cookie = 0, bool sync = false);

public:

    ::iTransformServer::byteArray getMessage(const ::iTransformServer::byteArray& cmd, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return end_getMessage(_iceI_begin_getMessage(cmd, context, ::IceInternal::dummyCallback, 0, true));
    }

    ::Ice::AsyncResultPtr begin_getMessage(const ::iTransformServer::byteArray& cmd, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _iceI_begin_getMessage(cmd, context, ::IceInternal::dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_getMessage(const ::iTransformServer::byteArray& cmd, const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_getMessage(cmd, ::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_getMessage(const ::iTransformServer::byteArray& cmd, const ::Ice::Context& context, const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_getMessage(cmd, context, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_getMessage(const ::iTransformServer::byteArray& cmd, const ::iTransformServer::Callback_iDataServer_getMessagePtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_getMessage(cmd, ::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_getMessage(const ::iTransformServer::byteArray& cmd, const ::Ice::Context& context, const ::iTransformServer::Callback_iDataServer_getMessagePtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_getMessage(cmd, context, cb, cookie);
    }

    ::iTransformServer::byteArray end_getMessage(const ::Ice::AsyncResultPtr& result);

private:

    ::Ice::AsyncResultPtr _iceI_begin_getMessage(const ::iTransformServer::byteArray&, const ::Ice::Context&, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& cookie = 0, bool sync = false);

public:

    /**
     * Obtains the Slice type ID corresponding to this interface.
     * @return A fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

protected:
    /// \cond INTERNAL

    virtual ::IceProxy::Ice::Object* _newInstance() const;
    /// \endcond
};

}

}

namespace iTransformServer
{

class iDataServer : public virtual ::Ice::Object
{
public:

    typedef iDataServerPrx ProxyType;
    typedef iDataServerPtr PointerType;

    virtual ~iDataServer();

    /**
     * Determines whether this object supports an interface with the given Slice type ID.
     * @param id The fully-scoped Slice type ID.
     * @param current The Current object for the invocation.
     * @return True if this object supports the interface, false, otherwise.
     */
    virtual bool ice_isA(const ::std::string& id, const ::Ice::Current& current = ::Ice::emptyCurrent) const;

    /**
     * Obtains a list of the Slice type IDs representing the interfaces supported by this object.
     * @param current The Current object for the invocation.
     * @return A list of fully-scoped type IDs.
     */
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& current = ::Ice::emptyCurrent) const;

    /**
     * Obtains a Slice type ID representing the most-derived interface supported by this object.
     * @param current The Current object for the invocation.
     * @return A fully-scoped type ID.
     */
    virtual const ::std::string& ice_id(const ::Ice::Current& current = ::Ice::emptyCurrent) const;

    /**
     * Obtains the Slice type ID corresponding to this class.
     * @return A fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

    virtual Result postMessage(const byteArray& cmd, const ::Ice::Current& current = ::Ice::emptyCurrent) = 0;
    /// \cond INTERNAL
    bool _iceD_postMessage(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    virtual byteArray getMessage(const byteArray& cmd, const ::Ice::Current& current = ::Ice::emptyCurrent) = 0;
    /// \cond INTERNAL
    bool _iceD_getMessage(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    /// \cond INTERNAL
    virtual bool _iceDispatch(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

protected:

    /// \cond STREAM
    virtual void _iceWriteImpl(::Ice::OutputStream*) const;
    virtual void _iceReadImpl(::Ice::InputStream*);
    /// \endcond
};

/// \cond INTERNAL
inline bool operator==(const iDataServer& lhs, const iDataServer& rhs)
{
    return static_cast<const ::Ice::Object&>(lhs) == static_cast<const ::Ice::Object&>(rhs);
}

inline bool operator<(const iDataServer& lhs, const iDataServer& rhs)
{
    return static_cast<const ::Ice::Object&>(lhs) < static_cast<const ::Ice::Object&>(rhs);
}
/// \endcond

}

/// \cond STREAM
namespace Ice
{

template<>
struct StreamableTraits< ::iTransformServer::Result>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 2;
    static const bool fixedLength = false;
};

template<typename S>
struct StreamWriter< ::iTransformServer::Result, S>
{
    static void write(S* ostr, const ::iTransformServer::Result& v)
    {
        ostr->write(v.decoder);
        ostr->write(v.data);
    }
};

template<typename S>
struct StreamReader< ::iTransformServer::Result, S>
{
    static void read(S* istr, ::iTransformServer::Result& v)
    {
        istr->read(v.decoder);
        istr->read(v.data);
    }
};

}
/// \endcond

namespace iTransformServer
{

/**
 * Type-safe asynchronous callback wrapper class used for calls to
 * IceProxy::iTransformServer::iDataServer::begin_postMessage.
 * Create a wrapper instance by calling ::iTransformServer::newCallback_iDataServer_postMessage.
 */
template<class T>
class CallbackNC_iDataServer_postMessage : public Callback_iDataServer_postMessage_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const Result&);

    CallbackNC_iDataServer_postMessage(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    /// \cond INTERNAL
    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        iDataServerPrx proxy = iDataServerPrx::uncheckedCast(result->getProxy());
        Result ret;
        try
        {
            ret = proxy->end_postMessage(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::CallbackNC<T>::_callback.get()->*_response)(ret);
        }
    }
    /// \endcond

private:

    Response _response;
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::iTransformServer::iDataServer::begin_postMessage.
 */
template<class T> Callback_iDataServer_postMessagePtr
newCallback_iDataServer_postMessage(const IceUtil::Handle<T>& instance, void (T::*cb)(const Result&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_iDataServer_postMessage<T>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::iTransformServer::iDataServer::begin_postMessage.
 */
template<class T> Callback_iDataServer_postMessagePtr
newCallback_iDataServer_postMessage(T* instance, void (T::*cb)(const Result&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_iDataServer_postMessage<T>(instance, cb, excb, sentcb);
}

/**
 * Type-safe asynchronous callback wrapper class with cookie support used for calls to
 * IceProxy::iTransformServer::iDataServer::begin_postMessage.
 * Create a wrapper instance by calling ::iTransformServer::newCallback_iDataServer_postMessage.
 */
template<class T, typename CT>
class Callback_iDataServer_postMessage : public Callback_iDataServer_postMessage_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const Result&, const CT&);

    Callback_iDataServer_postMessage(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    /// \cond INTERNAL
    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        iDataServerPrx proxy = iDataServerPrx::uncheckedCast(result->getProxy());
        Result ret;
        try
        {
            ret = proxy->end_postMessage(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::Callback<T, CT>::_callback.get()->*_response)(ret, CT::dynamicCast(result->getCookie()));
        }
    }
    /// \endcond

private:

    Response _response;
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::iTransformServer::iDataServer::begin_postMessage.
 */
template<class T, typename CT> Callback_iDataServer_postMessagePtr
newCallback_iDataServer_postMessage(const IceUtil::Handle<T>& instance, void (T::*cb)(const Result&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_iDataServer_postMessage<T, CT>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::iTransformServer::iDataServer::begin_postMessage.
 */
template<class T, typename CT> Callback_iDataServer_postMessagePtr
newCallback_iDataServer_postMessage(T* instance, void (T::*cb)(const Result&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_iDataServer_postMessage<T, CT>(instance, cb, excb, sentcb);
}

/**
 * Type-safe asynchronous callback wrapper class used for calls to
 * IceProxy::iTransformServer::iDataServer::begin_getMessage.
 * Create a wrapper instance by calling ::iTransformServer::newCallback_iDataServer_getMessage.
 */
template<class T>
class CallbackNC_iDataServer_getMessage : public Callback_iDataServer_getMessage_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const byteArray&);

    CallbackNC_iDataServer_getMessage(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    /// \cond INTERNAL
    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        iDataServerPrx proxy = iDataServerPrx::uncheckedCast(result->getProxy());
        byteArray ret;
        try
        {
            ret = proxy->end_getMessage(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::CallbackNC<T>::_callback.get()->*_response)(ret);
        }
    }
    /// \endcond

private:

    Response _response;
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::iTransformServer::iDataServer::begin_getMessage.
 */
template<class T> Callback_iDataServer_getMessagePtr
newCallback_iDataServer_getMessage(const IceUtil::Handle<T>& instance, void (T::*cb)(const byteArray&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_iDataServer_getMessage<T>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::iTransformServer::iDataServer::begin_getMessage.
 */
template<class T> Callback_iDataServer_getMessagePtr
newCallback_iDataServer_getMessage(T* instance, void (T::*cb)(const byteArray&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_iDataServer_getMessage<T>(instance, cb, excb, sentcb);
}

/**
 * Type-safe asynchronous callback wrapper class with cookie support used for calls to
 * IceProxy::iTransformServer::iDataServer::begin_getMessage.
 * Create a wrapper instance by calling ::iTransformServer::newCallback_iDataServer_getMessage.
 */
template<class T, typename CT>
class Callback_iDataServer_getMessage : public Callback_iDataServer_getMessage_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const byteArray&, const CT&);

    Callback_iDataServer_getMessage(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    /// \cond INTERNAL
    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        iDataServerPrx proxy = iDataServerPrx::uncheckedCast(result->getProxy());
        byteArray ret;
        try
        {
            ret = proxy->end_getMessage(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::Callback<T, CT>::_callback.get()->*_response)(ret, CT::dynamicCast(result->getCookie()));
        }
    }
    /// \endcond

private:

    Response _response;
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::iTransformServer::iDataServer::begin_getMessage.
 */
template<class T, typename CT> Callback_iDataServer_getMessagePtr
newCallback_iDataServer_getMessage(const IceUtil::Handle<T>& instance, void (T::*cb)(const byteArray&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_iDataServer_getMessage<T, CT>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::iTransformServer::iDataServer::begin_getMessage.
 */
template<class T, typename CT> Callback_iDataServer_getMessagePtr
newCallback_iDataServer_getMessage(T* instance, void (T::*cb)(const byteArray&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_iDataServer_getMessage<T, CT>(instance, cb, excb, sentcb);
}

}

#endif

#include <IceUtil/PopDisableWarnings.h>
#endif
